# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_bart_preprocessing.ipynb.

# %% auto 0
__all__ = ['method_size_vector', 'foo']

# %% ../nbs/00_bart_preprocessing.ipynb 9
def method_size_vector( method_vector ):
    '''Return the size of the tokens for a give method based on id
        Assuming that method_vector is an array of tokens
    '''
    input_ids = [ len(mtd) for mtd in method_vector ]
    return input_ids

# %% ../nbs/00_bart_preprocessing.ipynb 17
def foo(): pass
